language: java
before_install:
- git clone https://github.com/garethahealy/hawkular-client-java.git
- cd hawkular-client-java
- mvn clean install -DskipTests
install: mvn clean install -Dgpg.skip=true -DskipTests
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
