spec:
  replicas: 1
  template:
    spec:
      containers:
      - livenessProbe:
          httpGet:
            path: "/camel/hello"
            port: 8080
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: "/camel/hello"
            port: 8080
          initialDelaySeconds: 10
