#!/bin/sh

echo " -----> Post Assemble"

# Global S2I variable setup
source /tmp/src/.s2i/bin/s2i-setup

if [ -f "${S2I_SOURCE_DIR}/configuration/settings.xml" ]; then
  MAVEN_EXTRA_ARGS="-s ${S2I_SOURCE_DIR}/configuration/settings.xml"
  echo "Using custom maven settings from ${S2I_SOURCE_DIR}/configuration/settings.xml"
fi

mvn -f ${S2I_SOURCE_DIR}/pom.xml dependency:copy-dependencies -Pdownload-agent -DoutputDirectory=${DEPLOYMENTS_DIR}/bin ${MAVEN_EXTRA_ARGS}
